version: '2'
services:
    ohmage-app:
        image: ohmage
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ohmage-postgresql:5432/Ohmage
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ohmage-elasticsearch:9300
        ports:
            - 8080:8080
    ohmage-postgresql:
        extends:
            file: postgresql.yml
            service: ohmage-postgresql
    ohmage-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ohmage-elasticsearch
