dataStore: mongo


server:
  port: 8083

application:
  url: http://192.168.99.101:8082/dsu/
internalShimServer:
  url: http://192.168.99.101:8084/

spring:
  application:
    name: Open mHealth DSU resource server
  data:
    mongodb:
      host: 192.168.99.101
      database: omh
      #port: 27017
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.101:5432/omh
    username: postgres
    password: postgres

ohmageomh:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.101:5432/ohmage
    username: postgres
    password: postgres


multipart:
  maxFileSize: 50MB
  maxRequestSize: 50MB

http:
  mappers:
    jsonPrettyPrint: true


logging:
  path: /var/log/ohmage-resource/
  level:
    org.springframework: INFO